version: '3.9'

services:
  nginx:
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 4
      restart_policy:
        conditions: any
        parallelism: 2
        delay: 15s
    build: 
      context: .
      args:
        NODE_ENV: 'production'
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: node server.js
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  
