version: '3.9'
services:
  node-app:
    build: .
    ports:
      - "4000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
      # environment:
      # - PORT=3000
    env_file:
      - ./.env

networks:
  default:
    name: my_network
    external: true
