version: '3.9'

services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: 'development'
    env_file:
      - ./.dev.env
    volumes: 
      - ./:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    env_file:
      - ./.dev.env