version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  depends_on:
    - node-app
  
  node-app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes: 
      - db-data:/data/db

  redis:
    image: redis

networks:
  default:
    name: my_network
    external: true

volumes: 
  db-data: